# Generated by Django 2.2 on 2019-04-19 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_auto_20190419_0047'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='avatar',
            field=models.TextField(default='test'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='article',
            name='image_url',
            field=models.TextField(default='test'),
            preserve_default=False,
        ),
    ]
